[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "smart-host"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "sqlalchemy",
    "uvicorn==0.27.0.post1",
]
